#!/bin/sh
# set -x

### Config ###

# shellmarks directory. uses ~/.local/share/shellmarks if not set
SH_MARKS=${SH_MARKS:-${XDG_DATA_HOME:-$HOME/.local/share}/shellmarks}

# colors
# For a list of ANSI color codes, check the link below
# https://gist.github.com/Prakasaka/219fe5695beeb4d6311583e79933a009
col_error="\033[1;31m"     # Red
col_name="\033[1;33m"      # Yellow
col_path="\033[1;34m"      # Blue
col_reset="\033[m"         # Don't change this


### Functions ###

die() {
  [ -n "$1" ] &&
    printf "${col_error}%s${col_reset}\n" "$@" >/dev/stderr
  exit 1
}

symlink_resolve() {
  # this will fail epically if the filename has "->" in it
  ls -l "${SH_MARKS}/${1}" | sed 's|.* -> ||g'
}

bk_add() {
  [ -z "$1" ] && die "No name given"
  [ -e "${SH_MARKS}/${1}" ] &&
    die "${1} already exists"
  ln -s "$PWD" "${SH_MARKS}/${1}"
}

bk_remove() {
  [ -z "$1" ] && die "Nothing to remove"
  [ ! -h "${SH_MARKS}/${1}" ] &&
    die "${1} doesn't appear to be a symlink..."
  rm -f "${SH_MARKS}/${1}"
}

bk_cd() {
  [ -z "$1" ] && die "No argument given"
  [ ! -h "${SH_MARKS}/${1}" ] &&
    die "${1} doesn't appear to be a symlink..."
  symlink_resolve "$1"
}

bk_list() {
  cd "${SH_MARKS}" || die "Could not cd into ${SH_MARKS}"
  for file in *; do
    [ -e "$file" ] && [ -h "$file" ] &&
      printf "${col_name}%s -> ${col_path}" "$file" &&
      symlink_resolve "$file" && printf "${col_reset}"
  done
}

### main ###

[ -d "$SH_MARKS" ] ||
  mkdir -p "$SH_MARKS" ||
  die "Cannot create directory $SH_MARKS"

[ "$1" = "-c" ] && shift &&
  unset col_error col_name col_path col_reset

case "$1" in
  "add")
    bk_add "$2"
    ;;
  "rm")
    bk_remove "$2"
    ;;
  "cd")
    bk_cd "$2"
    ;;
  "ls")
    bk_list
    ;;
  *)
    die "INVALID COMMAND: $1"
    ;;
esac
