#!/bin/sh
# set -x

### Config ###

# shellmarks directory. uses ~/.local/share/shellmarks if not set
SH_MARKS=${SH_MARKS:-${XDG_DATA_HOME:-$HOME/.local/share}/shellmarks}


### Functions ###

die() {
  [ -n "$1" ] &&
    printf '%s\n' "$@" >/dev/stderr
  exit 1
}

bk_add() {
  [ -z "$1" ] && die "No name given"
  [ -e "${SH_MARKS}/${1}" ] &&
    die "${1} already exists"
  ln -s "$PWD" "${SH_MARKS}/${1}"
}

bk_remove() {
  [ -z "$1" ] && die "Nothing to remove"
  [ ! -h "${SH_MARKS}/${1}" ] &&
    die "${1} doesn't appear to be a symlink..."
  rm -f "${SH_MARKS}/${1}"
}

bk_cd() {
  [ -z "$1" ] && die "No argument given"
  [ ! -h "${SH_MARKS}/${1}" ] &&
    die "${1} doesn't appear to be a symlink..."
  echo "${SH_MARKS}/${1}"
}

### main ###

[ -d "$SH_MARKS" ] ||
  mkdir -p "$SH_MARKS" ||
  die "Cannot create directory $SH_MARKS"

case "$1" in
  "add")
    bk_add "$2"
    ;;
  "rm")
    bk_remove "$2"
    ;;
  "cd")
    bk_cd "$2"
    ;;
esac
