#!/bin/sh
#
## Copyright 2021 NRK
## Licensed under GPL v3. See LICENSE for more details.
# set -x

### Config ###

# shellmarks directory. uses ~/.local/share/shellmarks if not set
SH_MARKS=${SH_MARKS:-${XDG_DATA_HOME:-$HOME/.local/share}/shellmarks}

# colors
# For a list of ANSI color codes, check the link below
# https://gist.github.com/Prakasaka/219fe5695beeb4d6311583e79933a009
col_error="\033[1;31m"     # Red
col_name="\033[1;33m"      # Yellow
col_path="\033[0;34m"      # Blue
col_reset="\033[m"         # Don't change this


### Functions ###

die() {
  [ -n "$1" ] &&
    printf "${col_error}%s${col_reset}\n" "$@" >/dev/stderr
  exit 1
}

symlink_resolve() {
  [ "${1#*->}" = "$1" 2>/dev/null ] ||
    die "Filename contains \"->\" ... Unacceptable!"
  resolved="$(ls -dl "${SH_MARKS}/${1}")"
  echo "${resolved#* -> }"
  unset resolved
}

symlink_or_die() {
  [ ! -e "${SH_MARKS}/${1}" ] &&
    die "${1} doesn't exist"
  [ ! -h "${SH_MARKS}/${1}" ] &&
    die "${1} doesn't appear to be a symlink..."
}

bk_add() {
  [ -z "$1" ] && die "No name given"
  [ -e "${SH_MARKS}/${1}" ] &&
    die "${1} already exists"
  target="${2:-$PWD}"
  ln -s "$target" "${SH_MARKS}/${1}"
}

bk_remove() {
  [ -z "$1" ] && die "Nothing to remove"
  symlink_or_die "$1"
  rm -f "${SH_MARKS}/${1}"
}

bk_path() {
  [ -z "$1" ] && die "No argument given"
  symlink_or_die "$1"
  symlink_resolve "$1"
}

bk_list() {
  cd "${SH_MARKS}" || die "Could not cd into ${SH_MARKS}"
  [ -z "$1" ] && arrow=" -> "
  for file in *; do
    [ -e "$file" ] && [ -h "$file" ] &&
      printf "${col_name}%s${arrow}${col_path}${1}" "$file" &&
      [ -z "$1" ] && symlink_resolve "$file"
  done
  printf "${col_reset}"
}

### main ###

[ -d "$SH_MARKS" ] ||
  mkdir -p "$SH_MARKS" ||
  die "Cannot create directory $SH_MARKS"

[ "$1" = "-c" ] && shift &&
  unset col_error col_name col_path col_reset

case "$1" in
  "add")
    bk_add "$2" "$3"
    ;;
  "rm")
    bk_remove "$2"
    ;;
  "path")
    bk_path "$2"
    ;;
  "ls")
    [ "$2" = "-n" ] && name_only="\n"
    bk_list "$name_only"
    ;;
  *)
    die "INVALID COMMAND: $1"
    ;;
esac
